config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # you map a HTTP verb / URL combo to a controller + action (method)
  # get '/' => 'welcome#index'
  root 'welcome#index'
  # get({'/' => 'welcome#index'})

  # resources :dashboard, only: [:index], controller: 'admin/dashboard'
  namespace :admin do
    resources :dashboard, only: [:index]
  end

  # the above route maps any 'GET' request with '/' URL to the index action within the WelcomeController (action is a method defined within the controller class)
  # the above can be called DSL (Domain Specific Language). It's just Ruby it's not a special programming language, just Ruby. The Ruby is written in a way that looks like its own language
  get '/contact' => 'welcome#contact_us'
  post '/contact_submit' => 'welcome#contact_submit'
  get '/about' => 'welcome#about_us', as: :aboutus


  resources :questions do
    post :search, on: :collection
    # this creates a set of 'answers' routes nested within the 'questions' routes. This will make all the 'answers' routes
    resources :answers, only: [:create, :destroy]
  end


  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  # this line generates all routes below
  # post   '/questions'          => 'questions#create', as: :questions
  # get    '/questions'          => 'questions#index'
  # get    '/questions/new'      => 'questions#new',    as: :new_question
  # get    '/questions/:id'      => 'questions#show',   as: :question
  # get    '/questions/:id/edit' => 'questions#edit',   as: :edit_question
  # patch  '/questions/:id'      => 'questions#update'
  # delete '/questions/:id'      => 'questions#destroy'

  # post   '/questions/:question_id/answers' => 'answers#create'
  # delete '/questions/:question_id/answers/:id' => 'answers#destroy'
end

app/models/question.rb
class Question < ApplicationRecord

  #this sets up one-to-many association between the question and the answer in this case a question has many answers (note that to set a one-to-many association you will have to pluralize 'answer' - Rails convention)
  # we will have many handy methods to help us query associated records. for instance we can do: q = Question.last; answers = q.answers
  # the line above will fetch all the answers associated with question: q
  # it's highly recomended that you add the 'dependent' option to the association which tells Rails what to do when you delete a question that has answers associated with it, the most popular options are:
  # destroy: which will delete all associated answers before deleteing the question
  # nullify: which will update all the 'question_id' fields on the associated answers to become 'NULL' before deleting the question
  has_many :answers, lambda { order(created_at: :desc) }, dependent: :destroy
  belongs_to :user

  validates(:title, { presence: { message: 'must be given!' },
                      uniqueness: true })
  validates(:body, { presence: true, length: {minimum: 3} })
  validates(:view_count, { presence: true, numericality: { greater_than_or_equal_to: 0 } })
  validate :no_monkey

  after_initialize(:set_view_count)

  private
  def no_monkey
    if title.present? && title.downcase.include?('monkey')
      errors.add(:title, "No monkeys please!")
    end
  end

  def set_view_count
    self.view_count ||= 0;
  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  # this will execute the method 'find_question' before it executes the action
  # if you give it 'only' or 'except' options then it will only include or only exclude certain actions
  before_action :find_question, only: [:show, :edit, :destroy, :update]
  before_action :authorize, only: [:edit, :destroy, :update]

  def new
    # by default this will render app/views/questions/new.html.erb
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      flash[:notice] = 'Question created successfully'
      redirect_to question_path({ id: @question.id })
    else
      # this will force Rails to render: app/views/questions/new.html.erb
      # instead of the default: app/views/questions/create.html.erb
      flash.now[:alert] = 'Please fix messages below'
      render :new
    end
  end

  def show
    @answer = Answer.new
  end

  def index
    @questions = Question.order(created_at: :desc)
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to question_path(@question), notice: 'Question updated!'
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Question deleted!'
  end

  private
  def question_params
    params.require(:question).permit([:title, :body])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def authorize
    if cannot?(:manage, @question)
      redirect_to root_path, alert: 'Not authorized!'
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<p><%= @question.errors.full_messages.join(', ') %></p>
<%= form_for @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
<%= render 'form' %>

app/views/questions/index.html.erb
<h1>All Questions</h1>

<% @questions.each do |q| %>
  <%= link_to q.title, question_path(q) %>
  <hr>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%# form_for is a Rails helper (built-in) generate a form to create or updated_at a record in the database through a controller. form_for expects to be given an ActiveRecord object as its first argument %>
<%# if the object is not persisted then the form will use POST request and the URL will be the create action path which is in this case questions_path %>
<%# we also have access to the 'f' object which eases creating fields for the form. the field will be automatically pre-popuated with any data set in the object (such as title / body). It will also automatically set special 'name' attributes to the generated field. %>
<%= render 'form' %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.body %></p>

<% if user_signed_in? && @question.user_id == current_user.id %>
  <%= link_to 'Edit', edit_question_path(@question) %>
  <%= link_to 'Delete', question_path(@question), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<hr>
<h2>Answers</h2>
<h3>Create New Answer</h3>
<%= @answer.errors.full_messages.join(', ') %>
<%= form_for [@question, @answer] do |f| %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>


<hr>
<% @question.answers.each do |ans| %>
  <%= ans.body %>
  <%= link_to 'delete', question_answer_path(@question, ans), method: :delete, data: { confirm: 'Are you sure?' } %>
  <hr>
<% end %>